version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: install-glaciary
          command: 'sudo npm install -g glaciary'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install
          command: cd test && npm install
      - run:
          name: start
          command: cd test && npm start
      - run:
          name: ls
          command: cd test && ls