version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm'
      - run:
          name: install-glaciary
          command: 'sudo npm install -g glaciary'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: cd-to-test
          command: cd .circleci/test-app && npm install && npm start